language: node_js
before_install: npm install npm@3 -g
env:
  - CXX=g++-4.8
addons:
    apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.8
node_js:
  - "4.2.6"
services:
  - redis-server
